kazi:
    resource: "@KaziBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin #accessible from localhost:8000/admin

#FOS User Bundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#phax for commandline calling controller
phax:
    resource: "@PhaxCoreBundle/Resources/config/routing.yml"

base_url:
    pattern:  /