<?php

namespace AppBundle\Entity;

/**
 * AgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeRepository extends \Doctrine\ORM\EntityRepository
{
}
