<?php

namespace AppBundle\Entity;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
     /**
     * Get answers
     *
     * @return Answers
     */
    public function findAnswersByGroupId($id)
    {
        
        $repository = $this->getDoctrine()->getRepository('AppBundle:Answer');
        $answers = $repository->findByAnswerGroup($id);
        return $answers;
    }

}
