<?php

namespace AppBundle\Entity;

/**
 * AnswerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
