<?php

namespace AppBundle\Entity;

/**
 * CardtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
