<?php

namespace AppBundle\Entity;

/**
 * CardholderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardholderRepository extends \Doctrine\ORM\EntityRepository
{
}
