<?php

namespace AppBundle\Entity;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
//use Symfony\Component\HttpFoundation\Response;
/**
 * DistrictRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get shapeinfo
     * @return string
     */
    public function getShapeinfo($id)
    {
        $district = $this->find($id);
        $response = array();
        //$response["id"] = $
            
        return $district->getShape();
    }
}
