<?php

namespace AppBundle\Entity;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get shapeinfo
     *
     * @return string
     */
    public function getShapeinfo($id)
    {
        $district = $this->find($id);
        $response = array();
        //$response["id"] = $
            
        return $district->getShape();
    }
}
