<?php

namespace AppBundle\Entity;

/**
 * EthnicityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EthnicityRepository extends \Doctrine\ORM\EntityRepository
{
}
