<?php

namespace AppBundle\Entity;

/**
 * HouseholdheadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseholdheadRepository extends \Doctrine\ORM\EntityRepository
{
}
