<?php

namespace AppBundle\Entity;

/**
 * InterviewerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewerRepository extends \Doctrine\ORM\EntityRepository
{
}
