<?php

namespace AppBundle\Entity;

/**
 * IssueMapDistrictsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueMapDistrictsRepository extends \Doctrine\ORM\EntityRepository
{
}
