<?php

namespace AppBundle\Entity;

/**
 * IssueInfographicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueInfographicsRepository extends \Doctrine\ORM\EntityRepository
{
}
