<?php

namespace AppBundle\Entity;

/**
 * IssuePeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuePeopleRepository extends \Doctrine\ORM\EntityRepository
{
}
