<?php

namespace AppBundle\Entity;

/**
 * IssueQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
