<?php

namespace AppBundle\Entity;

/**
 * VdcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdcRepository extends \Doctrine\ORM\EntityRepository
{
}
